title: Invasive Species in East Brunswick
theme: minima
author: Jonathan Yu 
email: jyu@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Invasive species in the U.S. pose a threat to different industries and wildlife. 

# social links
github_username:  Joofers

show_excerpts: true # set to false to remove excerpts on the homepage
