title: Invasive Species in East Brunswick
theme: minima
author: Jonathan Y. 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dragonflies have been identified as an invasive species that can be found in East Brunswick. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
